name: flexypack
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^4.0.1
  flutter_email_sender: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flip_card: ^0.4.4

  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # declaración de Logo
  assets:
    #rutas de imagenes
    - assets/images/logo/logo.png
    #1 Garrafon
    - assets/images/garrafon/pet/
    - assets/images/garrafon/pvc/
    #2 Botellas
    - assets/images/botellas/
    #3 Tapas
    - assets/images/tapas/
    #4 sellos
    - assets/images/sellos/
    #5 porta filtro
    - assets/images/portafiltro/
    #6 ozonos
    - assets/images/ozonos/
    #7 maquinas para sellado
    - assets/images/maquinasparasellado/
    #8 insumos varios maquinaria
    - assets/images/insumosvariosmaquinaria/
    #9 insumos varios
    - assets/images/insumosvarios/
    #10 insumos quimicos
    - assets/images/insumosquimicos/
    #11 filtros
    - assets/images/filtros/
    #12 etiquetas
    - assets/images/etiquetas/
    #13 equipos de contraccion
    - assets/images/equiposdecontraccion/
    #14 enfriadores
    - assets/images/enfriadores/
    #15 division de metales
    - assets/images/divisiondemetales/
    #16 cisterna
    - assets/images/cisterna/
    #17 calcomanias
    - assets/images/calcamonias/
    #18 bolsa de hielo
    - assets/images/bolsadehielo/  



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
